# DS NOV 2023 
  Carn PRice prediction

In [7]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import os
import warnings
warnings.filterwarnings('ignore')


In [2]:
print (os.getcwd())



C:\Users\Lenovo\Desktop\sociology


In [5]:
df=pd.read_csv("audi.csv")
display(df)




model  year  price transmission  mileage fuelType  tax   mpg  engineSize
0        A1  2017  12500       Manual    15735   Petrol  150  55.4         1.4
1        A6  2016  16500    Automatic    36203   Diesel   20  64.2         2.0
2        A1  2016  11000       Manual    29946   Petrol   30  55.4         1.4
3        A4  2017  16800    Automatic    25952   Diesel  145  67.3         2.0
4        A3  2019  17300       Manual     1998   Petrol  145  49.6         1.0
...     ...   ...    ...          ...      ...      ...  ...   ...         ...
10663    A3  2020  16999       Manual     4018   Petrol  145  49.6         1.0
10664    A3  2020  16999       Manual     1978   Petrol  150  49.6         1.0
10665    A3  2020  17199       Manual      609   Petrol  150  49.6         1.0
10666    Q3  2017  19499    Automatic     8646   Petrol  150  47.9         1.4
10667    Q3  2016  15999       Manual    11855   Petrol  150  47.9         1.4

[10668 rows x 9 columns]

In [10]:
print (len(df))


10668


In [11]:
display (df.shape)


(10668, 9)

In [12]:
display (df.dtypes )


model            object
year              int64
price             int64
transmission     object
mileage           int64
fuelType         object
tax               int64
mpg             float64
engineSize      float64
dtype: object

In [13]:
display (df.isna().sum() )



model           0
year            0
price           0
transmission    0
mileage         0
fuelType        0
tax             0
mpg             0
engineSize      0
dtype: int64

In [14]:
print (df.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10668 entries, 0 to 10667
Data columns (total 9 columns):
 #   Column        Non-Null Count  Dtype  
---  ------        --------------  -----  
 0   model         10668 non-null  object 
 1   year          10668 non-null  int64  
 2   price         10668 non-null  int64  
 3   transmission  10668 non-null  object 
 4   mileage       10668 non-null  int64  
 5   fuelType      10668 non-null  object 
 6   tax           10668 non-null  int64  
 7   mpg           10668 non-null  float64
 8   engineSize    10668 non-null  float64
dtypes: float64(2), int64(4), object(3)
memory usage: 750.2+ KB
None


In [15]:
display (df.describe ())


year          price        mileage           tax           mpg  \
count  10668.000000   10668.000000   10668.000000  10668.000000  10668.000000   
mean    2017.100675   22896.685039   24827.244001    126.011436     50.770022   
std        2.167494   11714.841888   23505.257205     67.170294     12.949782   
min     1997.000000    1490.000000       1.000000      0.000000     18.900000   
25%     2016.000000   15130.750000    5968.750000    125.000000     40.900000   
50%     2017.000000   20200.000000   19000.000000    145.000000     49.600000   
75%     2019.000000   27990.000000   36464.500000    145.000000     58.900000   
max     2020.000000  145000.000000  323000.000000    580.000000    188.300000   

         engineSize  
count  10668.000000  
mean       1.930709  
std        0.602957  
min        0.000000  
25%        1.500000  
50%        2.000000  
75%        2.000000  
max        6.300000

In [16]:
X = df.iloc[:,[0,1,3,4,5,6,7,8]].values
display (X.shape)
display (X)


(10668, 8)

array([[' A1', 2017, 'Manual', ..., 150, 55.4, 1.4],
       [' A6', 2016, 'Automatic', ..., 20, 64.2, 2.0],
       [' A1', 2016, 'Manual', ..., 30, 55.4, 1.4],
       ...,
       [' A3', 2020, 'Manual', ..., 150, 49.6, 1.0],
       [' Q3', 2017, 'Automatic', ..., 150, 47.9, 1.4],
       [' Q3', 2016, 'Manual', ..., 150, 47.9, 1.4]], dtype=object)

In [18]:
Y = df.iloc[:,[2]].values
display (Y.shape)
display (Y)


(10668, 1)

array([[12500],
       [16500],
       [11000],
       ...,
       [17199],
       [19499],
       [15999]], dtype=int64)

In [19]:
display(pd.DataFrame(X).head(5))


0     1          2      3       4    5     6    7
0   A1  2017     Manual  15735  Petrol  150  55.4  1.4
1   A6  2016  Automatic  36203  Diesel   20  64.2  2.0
2   A1  2016     Manual  29946  Petrol   30  55.4  1.4
3   A4  2017  Automatic  25952  Diesel  145  67.3  2.0
4   A3  2019     Manual   1998  Petrol  145  49.6  1.0

In [20]:
from sklearn.preprocessing import LabelEncoder
le1 = LabelEncoder()
X[:,0] = le1.fit_transform(X[:,0])
le2 = LabelEncoder()
X[:,-4] = le2.fit_transform(X[:,-4])
display (X)


array([[0, 2017, 'Manual', ..., 150, 55.4, 1.4],
       [5, 2016, 'Automatic', ..., 20, 64.2, 2.0],
       [0, 2016, 'Manual', ..., 30, 55.4, 1.4],
       ...,
       [2, 2020, 'Manual', ..., 150, 49.6, 1.0],
       [9, 2017, 'Automatic', ..., 150, 47.9, 1.4],
       [9, 2016, 'Manual', ..., 150, 47.9, 1.4]], dtype=object)

In [21]:
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer
ct = ColumnTransformer(transformers = [('encoder',OneHotEncoder(),[2])],remainder='passthrough')
X = ct.fit_transform(X)
display (X.shape)
display (pd.DataFrame(X))


(10668, 10)

0    1    2  3     4      5  6    7     8    9
0      0.0  1.0  0.0  0  2017  15735  2  150  55.4  1.4
1      1.0  0.0  0.0  5  2016  36203  0   20  64.2  2.0
2      0.0  1.0  0.0  0  2016  29946  2   30  55.4  1.4
3      1.0  0.0  0.0  3  2017  25952  0  145  67.3  2.0
4      0.0  1.0  0.0  2  2019   1998  2  145  49.6  1.0
...    ...  ...  ... ..   ...    ... ..  ...   ...  ...
10663  0.0  1.0  0.0  2  2020   4018  2  145  49.6  1.0
10664  0.0  1.0  0.0  2  2020   1978  2  150  49.6  1.0
10665  0.0  1.0  0.0  2  2020    609  2  150  49.6  1.0
10666  1.0  0.0  0.0  9  2017   8646  2  150  47.9  1.4
10667  0.0  1.0  0.0  9  2016  11855  2  150  47.9  1.4

[10668 rows x 10 columns]

In [22]:
display (pd.DataFrame(X))


0    1    2  3     4      5  6    7     8    9
0      0.0  1.0  0.0  0  2017  15735  2  150  55.4  1.4
1      1.0  0.0  0.0  5  2016  36203  0   20  64.2  2.0
2      0.0  1.0  0.0  0  2016  29946  2   30  55.4  1.4
3      1.0  0.0  0.0  3  2017  25952  0  145  67.3  2.0
4      0.0  1.0  0.0  2  2019   1998  2  145  49.6  1.0
...    ...  ...  ... ..   ...    ... ..  ...   ...  ...
10663  0.0  1.0  0.0  2  2020   4018  2  145  49.6  1.0
10664  0.0  1.0  0.0  2  2020   1978  2  150  49.6  1.0
10665  0.0  1.0  0.0  2  2020    609  2  150  49.6  1.0
10666  1.0  0.0  0.0  9  2017   8646  2  150  47.9  1.4
10667  0.0  1.0  0.0  9  2016  11855  2  150  47.9  1.4

[10668 rows x 10 columns]

In [23]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X = sc.fit_transform(X)
display (pd.DataFrame(X))


0         1         2         3         4         5         6  \
0     -0.583268  1.200728 -0.712333 -1.123544 -0.046450 -0.386836  1.050783   
1      1.714479 -0.832828 -0.712333 -0.160831 -0.507834  0.483989 -0.954181   
2     -0.583268  1.200728 -0.712333 -1.123544 -0.507834  0.217781  1.050783   
3      1.714479 -0.832828 -0.712333 -0.545916 -0.046450  0.047853 -0.954181   
4     -0.583268  1.200728 -0.712333 -0.738459  0.876318 -0.971285  1.050783   
...         ...       ...       ...       ...       ...       ...       ...   
10663 -0.583268  1.200728 -0.712333 -0.738459  1.337702 -0.885343  1.050783   
10664 -0.583268  1.200728 -0.712333 -0.738459  1.337702 -0.972136  1.050783   
10665 -0.583268  1.200728 -0.712333 -0.738459  1.337702 -1.030381  1.050783   
10666  1.714479 -0.832828 -0.712333  0.609339 -0.046450 -0.688442  1.050783   
10667 -0.583268  1.200728 -0.712333  0.609339 -0.507834 -0.551913  1.050783   

              7         8         9  
0      0.357147  0.357550 -0.880218  
1     -1.578323  1.037130  0.114925  
2     -1.429440  0.357550 -0.880218  
3      0.282706  1.276528  0.114925  
4      0.282706 -0.090355 -1.543647  
...         ...       ...       ...  
10663  0.282706 -0.090355 -1.543647  
10664  0.357147 -0.090355 -1.543647  
10665  0.357147 -0.090355 -1.543647  
10666  0.357147 -0.221637 -0.880218  
10667  0.357147 -0.221637 -0.880218  

[10668 rows x 10 columns]

In [24]:
from sklearn.model_selection import train_test_split
(X_train,X_test,Y_train,Y_test) = train_test_split(X,Y,test_size=0.2,random_state=0)
print (X.shape, Y.shape)
print (X_train.shape, Y_train.shape)
print (X_test.shape, Y_test.shape)


(10668, 10) (10668, 1)
(8534, 10) (8534, 1)
(2134, 10) (2134, 1)


In [25]:

from sklearn.ensemble import RandomForestRegressor
regression = RandomForestRegressor(random_state=0)
regression.fit(X_train,Y_train)
display (regression)


RandomForestRegressor(random_state=0)

In [26]:
y_pred = regression.predict(X_test)
display (y_pred)


array([14337.15, 23450.35, 27330.07, ..., 46275.18, 31359.  ,  9929.62])

In [27]:
print(np.concatenate((y_pred.reshape(len(y_pred),1),Y_test.reshape(len(Y_test),1)),1))



[[14337.15 14998.  ]
 [23450.35 21950.  ]
 [27330.07 28990.  ]
 ...
 [46275.18 45995.  ]
 [31359.   30500.  ]
 [ 9929.62  8400.  ]]


In [28]:
from sklearn.metrics import r2_score,mean_absolute_error
print  ('R2 Score ', r2_score(Y_test, y_pred))
print  ('Mean Absolute Error', mean_absolute_error(Y_test,y_pred))


R2 Score  0.9536134841307546
Mean Absolute Error 1538.730980670462


In [29]:
from sklearn.linear_model import LinearRegression
reg = LinearRegression()
reg.fit(X_train,Y_train)
print(reg)


LinearRegression()


In [30]:
y_pred = reg.predict(X_test)
display (y_pred)


array([[13095.55234668],
       [29380.55234668],
       [31837.55234668],
       ...,
       [42652.55234668],
       [31554.55234668],
       [ 7329.55234668]])

In [31]:
print(np.concatenate((y_pred.reshape(len(y_pred),1),Y_test.reshape(len(Y_test),1)),1))


[[13095.55234668 14998.        ]
 [29380.55234668 21950.        ]
 [31837.55234668 28990.        ]
 ...
 [42652.55234668 45995.        ]
 [31554.55234668 30500.        ]
 [ 7329.55234668  8400.        ]]


In [32]:
from sklearn.metrics import r2_score,mean_absolute_error
print  ('R2 Score ', r2_score(Y_test, y_pred))
print  ('Mean Absolute Error', mean_absolute_error(Y_test,y_pred))


R2 Score  0.7915568279145352
Mean Absolute Error 3379.644179345178


In [33]:
y_pred = reg.predict(X)
display (y_pred)


array([[14660.55234668],
       [20566.55234668],
       [13842.55234668],
       ...,
       [19436.55234668],
       [20924.55234668],
       [16720.55234668]])

In [34]:
result = pd.concat([df,pd.DataFrame(y_pred)],axis=1)
display( result)


model  year  price transmission  mileage fuelType  tax   mpg  \
0        A1  2017  12500       Manual    15735   Petrol  150  55.4   
1        A6  2016  16500    Automatic    36203   Diesel   20  64.2   
2        A1  2016  11000       Manual    29946   Petrol   30  55.4   
3        A4  2017  16800    Automatic    25952   Diesel  145  67.3   
4        A3  2019  17300       Manual     1998   Petrol  145  49.6   
...     ...   ...    ...          ...      ...      ...  ...   ...   
10663    A3  2020  16999       Manual     4018   Petrol  145  49.6   
10664    A3  2020  16999       Manual     1978   Petrol  150  49.6   
10665    A3  2020  17199       Manual      609   Petrol  150  49.6   
10666    Q3  2017  19499    Automatic     8646   Petrol  150  47.9   
10667    Q3  2016  15999       Manual    11855   Petrol  150  47.9   

       engineSize             0  
0             1.4  14660.552347  
1             2.0  20566.552347  
2             1.4  13842.552347  
3             2.0  19843.552347  
4             1.0  17379.552347  
...           ...           ...  
10663         1.0  19219.552347  
10664         1.0  19306.552347  
10665         1.0  19436.552347  
10666         1.4  20924.552347  
10667         1.4  16720.552347  

[10668 rows x 10 columns]

In [35]:
from sklearn.ensemble import  ExtraTreesRegressor
ET_Model=ExtraTreesRegressor(n_estimators = 120)
ET_Model.fit(X_train,Y_train)
y_predict=ET_Model.predict(X_test)
from sklearn.metrics import r2_score,mean_absolute_error
print  ('R2 Score ', r2_score(Y_test, y_predict))
print  ('Mean Absolute Error', mean_absolute_error(Y_test,y_predict))


R2 Score  0.9551931846111889
Mean Absolute Error 1537.9375685983546


In [36]:
y_pred = reg.predict(X)
display (y_pred)
result = pd.concat([df,pd.DataFrame(y_pred)],axis=1)
display( result)


array([[14660.55234668],
       [20566.55234668],
       [13842.55234668],
       ...,
       [19436.55234668],
       [20924.55234668],
       [16720.55234668]])

model  year  price transmission  mileage fuelType  tax   mpg  \
0        A1  2017  12500       Manual    15735   Petrol  150  55.4   
1        A6  2016  16500    Automatic    36203   Diesel   20  64.2   
2        A1  2016  11000       Manual    29946   Petrol   30  55.4   
3        A4  2017  16800    Automatic    25952   Diesel  145  67.3   
4        A3  2019  17300       Manual     1998   Petrol  145  49.6   
...     ...   ...    ...          ...      ...      ...  ...   ...   
10663    A3  2020  16999       Manual     4018   Petrol  145  49.6   
10664    A3  2020  16999       Manual     1978   Petrol  150  49.6   
10665    A3  2020  17199       Manual      609   Petrol  150  49.6   
10666    Q3  2017  19499    Automatic     8646   Petrol  150  47.9   
10667    Q3  2016  15999       Manual    11855   Petrol  150  47.9   

       engineSize             0  
0             1.4  14660.552347  
1             2.0  20566.552347  
2             1.4  13842.552347  
3             2.0  19843.552347  
4             1.0  17379.552347  
...           ...           ...  
10663         1.0  19219.552347  
10664         1.0  19306.552347  
10665         1.0  19436.552347  
10666         1.4  20924.552347  
10667         1.4  16720.552347  

[10668 rows x 10 columns]

In [37]:
from sklearn.model_selection import RandomizedSearchCV
n_estimators = [int(x) for x in np.linspace(start = 80, stop = 1500, num = 10)]
max_features = ['auto', 'sqrt']
max_depth = [int(x) for x in np.linspace(6, 45, num = 5)]
min_samples_split = [2, 5, 10, 15, 100]
min_samples_leaf = [1, 2, 5, 10]


In [39]:
rand_grid={'n_estimators': n_estimators,
               'max_features': max_features,
               'max_depth': max_depth,
               'min_samples_split': min_samples_split,
               'min_samples_leaf': min_samples_leaf}
rf=RandomForestRegressor()
rCV=RandomizedSearchCV(estimator=rf,param_distributions=rand_grid,scoring='neg_mean_squared_error',n_iter=3,cv=3,random_state=42, n_jobs = 1)


In [40]:
display (rCV.fit(X_train,Y_train))


RandomizedSearchCV(cv=3, estimator=RandomForestRegressor(), n_iter=3, n_jobs=1,
                   param_distributions={'max_depth': [6, 15, 25, 35, 45],
                                        'max_features': ['auto', 'sqrt'],
                                        'min_samples_leaf': [1, 2, 5, 10],
                                        'min_samples_split': [2, 5, 10, 15,
                                                              100],
                                        'n_estimators': [80, 237, 395, 553, 711,
                                                         868, 1026, 1184, 1342,
                                                         1500]},
                   random_state=42, scoring='neg_mean_squared_error')

In [41]:
rf_pred=rCV.predict(X_test)
display (rf_pred)


array([14019.77380447, 23737.99802538, 28551.1432001 , ...,
       48096.43944566, 31312.55422296, 10055.92772238])

In [42]:
from sklearn.metrics import mean_absolute_error,mean_squared_error
print('MAE',mean_absolute_error(Y_test,rf_pred))
print('MSE',mean_squared_error(Y_test,rf_pred))


MAE 1505.4152851395713
MSE 5705986.622459673


In [43]:
display (r2_score(Y_test,rf_pred))


0.9584765521092762

In [44]:
pip install catboost


  Obtaining dependency information for catboost from https://files.pythonhosted.org/packages/e8/37/3afd3c02798734efcd7840bfa872d3efc06f5d5c92f9613fea3ff5b4311f/catboost-1.2.3-cp311-cp311-win_amd64.whl.metadata
  Obtaining dependency information for graphviz from https://files.pythonhosted.org/packages/de/5e/fcbb22c68208d39edff467809d06c9d81d7d27426460ebc598e55130c1aa/graphviz-0.20.1-py3-none-any.whl.metadata
   ---------------------------------------- 0.0/101.1 MB ? eta -:--:--
   ---------------------------------------- 0.1/101.1 MB 1.3 MB/s eta 0:01:18
   ---------------------------------------- 0.1/101.1 MB 2.8 MB/s eta 0:00:36
   ---------------------------------------- 0.3/101.1 MB 2.1 MB/s eta 0:00:48
   ---------------------------------------- 0.6/101.1 MB 3.2 MB/s eta 0:00:32
   ---------------------------------------- 0.8/101.1 MB 3.6 MB/s eta 0:00:28
    --------------------------------------- 1.3/101.1 MB 4.5 MB/s eta 0:00:23
    --------------------------------------- 1.4/

In [45]:
from catboost import CatBoostRegressor
cat=CatBoostRegressor()
print (cat.fit(X_train,Y_train))


Learning rate set to 0.057452
0:	learn: 11184.0694779	total: 142ms	remaining: 2m 21s
1:	learn: 10690.2138498	total: 152ms	remaining: 1m 15s
2:	learn: 10221.1011877	total: 159ms	remaining: 52.9s
3:	learn: 9778.8067263	total: 169ms	remaining: 42.1s
4:	learn: 9382.6454054	total: 175ms	remaining: 34.8s
5:	learn: 8989.9290587	total: 180ms	remaining: 29.8s
6:	learn: 8628.4892653	total: 183ms	remaining: 26s
7:	learn: 8280.9179062	total: 186ms	remaining: 23.1s
8:	learn: 7950.5476053	total: 189ms	remaining: 20.8s
9:	learn: 7636.7735365	total: 195ms	remaining: 19.3s
10:	learn: 7349.6084699	total: 199ms	remaining: 17.9s
11:	learn: 7084.0457263	total: 204ms	remaining: 16.8s
12:	learn: 6842.7060927	total: 212ms	remaining: 16.1s
13:	learn: 6608.0244743	total: 215ms	remaining: 15.2s
14:	learn: 6387.7285726	total: 218ms	remaining: 14.3s
15:	learn: 6170.1354894	total: 223ms	remaining: 13.7s
16:	learn: 5973.9133066	total: 227ms	remaining: 13.1s
17:	learn: 5780.4713044	total: 230ms	remaining: 12.6s
18:	l

184:	learn: 2385.2843416	total: 1.01s	remaining: 4.44s
185:	learn: 2384.0606488	total: 1.03s	remaining: 4.51s
186:	learn: 2381.7253049	total: 1.06s	remaining: 4.62s
187:	learn: 2380.6296772	total: 1.08s	remaining: 4.69s
188:	learn: 2377.6691116	total: 1.11s	remaining: 4.76s
189:	learn: 2376.6098548	total: 1.13s	remaining: 4.8s
190:	learn: 2373.3608150	total: 1.14s	remaining: 4.81s
191:	learn: 2371.9139000	total: 1.17s	remaining: 4.91s
192:	learn: 2369.5546632	total: 1.19s	remaining: 4.97s
193:	learn: 2366.3459170	total: 1.2s	remaining: 4.97s
194:	learn: 2362.9178905	total: 1.2s	remaining: 4.97s
195:	learn: 2360.1859250	total: 1.21s	remaining: 4.96s
196:	learn: 2359.2590139	total: 1.23s	remaining: 5s
197:	learn: 2357.0284087	total: 1.24s	remaining: 5.01s
198:	learn: 2353.8146557	total: 1.25s	remaining: 5.02s
199:	learn: 2353.1600869	total: 1.25s	remaining: 5.01s
200:	learn: 2350.2201701	total: 1.26s	remaining: 5.02s
201:	learn: 2347.3400692	total: 1.27s	remaining: 5.02s
202:	learn: 2345

345:	learn: 2138.1651205	total: 2.03s	remaining: 3.83s
346:	learn: 2136.6793748	total: 2.04s	remaining: 3.84s
347:	learn: 2134.9271288	total: 2.04s	remaining: 3.83s
348:	learn: 2133.4990990	total: 2.06s	remaining: 3.83s
349:	learn: 2132.9579709	total: 2.06s	remaining: 3.83s
350:	learn: 2131.3568877	total: 2.07s	remaining: 3.82s
351:	learn: 2130.0934606	total: 2.07s	remaining: 3.81s
352:	learn: 2129.1291428	total: 2.08s	remaining: 3.81s
353:	learn: 2127.2119683	total: 2.08s	remaining: 3.8s
354:	learn: 2126.2466287	total: 2.09s	remaining: 3.79s
355:	learn: 2125.9083128	total: 2.09s	remaining: 3.78s
356:	learn: 2125.6451110	total: 2.1s	remaining: 3.77s
357:	learn: 2123.9260800	total: 2.1s	remaining: 3.77s
358:	learn: 2122.2698937	total: 2.11s	remaining: 3.76s
359:	learn: 2120.6817881	total: 2.11s	remaining: 3.75s
360:	learn: 2120.4331669	total: 2.12s	remaining: 3.75s
361:	learn: 2118.9594319	total: 2.12s	remaining: 3.74s
362:	learn: 2118.1315547	total: 2.13s	remaining: 3.73s
363:	learn: 2

508:	learn: 2002.2660866	total: 2.81s	remaining: 2.71s
509:	learn: 2001.7655635	total: 2.82s	remaining: 2.71s
510:	learn: 2001.4857925	total: 2.83s	remaining: 2.7s
511:	learn: 2000.8821102	total: 2.83s	remaining: 2.7s
512:	learn: 2000.1964240	total: 2.84s	remaining: 2.69s
513:	learn: 1999.7786055	total: 2.84s	remaining: 2.69s
514:	learn: 1998.5400249	total: 2.84s	remaining: 2.68s
515:	learn: 1998.0114463	total: 2.85s	remaining: 2.67s
516:	learn: 1996.9762909	total: 2.85s	remaining: 2.67s
517:	learn: 1995.6335126	total: 2.86s	remaining: 2.66s
518:	learn: 1995.3818569	total: 2.86s	remaining: 2.65s
519:	learn: 1994.6836261	total: 2.87s	remaining: 2.65s
520:	learn: 1993.7077334	total: 2.87s	remaining: 2.64s
521:	learn: 1993.4826742	total: 2.87s	remaining: 2.63s
522:	learn: 1992.4700473	total: 2.88s	remaining: 2.62s
523:	learn: 1991.3567304	total: 2.88s	remaining: 2.62s
524:	learn: 1990.6762970	total: 2.89s	remaining: 2.61s
525:	learn: 1989.5606652	total: 2.89s	remaining: 2.6s
526:	learn: 1

699:	learn: 1894.3945945	total: 3.61s	remaining: 1.55s
700:	learn: 1893.8565117	total: 3.62s	remaining: 1.54s
701:	learn: 1893.2077595	total: 3.62s	remaining: 1.54s
702:	learn: 1892.9506973	total: 3.63s	remaining: 1.53s
703:	learn: 1892.0310965	total: 3.63s	remaining: 1.53s
704:	learn: 1891.6653710	total: 3.64s	remaining: 1.52s
705:	learn: 1891.2893392	total: 3.64s	remaining: 1.52s
706:	learn: 1890.8579018	total: 3.65s	remaining: 1.51s
707:	learn: 1890.4723481	total: 3.65s	remaining: 1.5s
708:	learn: 1889.4352253	total: 3.65s	remaining: 1.5s
709:	learn: 1888.9559607	total: 3.66s	remaining: 1.5s
710:	learn: 1888.4409118	total: 3.66s	remaining: 1.49s
711:	learn: 1887.9676716	total: 3.67s	remaining: 1.48s
712:	learn: 1887.7094590	total: 3.67s	remaining: 1.48s
713:	learn: 1887.3936179	total: 3.68s	remaining: 1.47s
714:	learn: 1887.0250097	total: 3.68s	remaining: 1.47s
715:	learn: 1885.9298356	total: 3.68s	remaining: 1.46s
716:	learn: 1885.6146034	total: 3.69s	remaining: 1.46s
717:	learn: 1

885:	learn: 1812.4607602	total: 4.4s	remaining: 566ms
886:	learn: 1811.8562410	total: 4.41s	remaining: 561ms
887:	learn: 1811.5294675	total: 4.41s	remaining: 557ms
888:	learn: 1811.0188588	total: 4.42s	remaining: 552ms
889:	learn: 1810.7853011	total: 4.45s	remaining: 550ms
890:	learn: 1810.2405183	total: 4.46s	remaining: 545ms
891:	learn: 1810.0319371	total: 4.46s	remaining: 540ms
892:	learn: 1809.8140306	total: 4.46s	remaining: 535ms
893:	learn: 1809.2706172	total: 4.47s	remaining: 530ms
894:	learn: 1808.7636476	total: 4.47s	remaining: 525ms
895:	learn: 1808.5795658	total: 4.48s	remaining: 520ms
896:	learn: 1808.2682456	total: 4.48s	remaining: 515ms
897:	learn: 1807.6999513	total: 4.49s	remaining: 510ms
898:	learn: 1807.1011318	total: 4.49s	remaining: 505ms
899:	learn: 1806.9458012	total: 4.49s	remaining: 499ms
900:	learn: 1806.4977533	total: 4.5s	remaining: 494ms
901:	learn: 1805.7089914	total: 4.5s	remaining: 489ms
902:	learn: 1805.3878730	total: 4.51s	remaining: 484ms
903:	learn: 1

In [46]:
cat_pred=cat.predict(X_test)
display (cat_pred)


array([13386.63817795, 24056.86842882, 28082.99514751, ...,
       45959.31234642, 31714.44751009,  9481.45994163])

In [47]:
display (r2_score(Y_test,cat_pred))



0.9641612028134969

In [48]:
import pickle 
pickle.dump(cat, open('model.pkl','wb'))


In [49]:
model=pickle.load(open('model.pkl','rb'))
print (model.predict (X_train))


[14256.69390956 29475.32741129 11911.12888914 ... 21406.16876331
 17189.65426694 44839.56117235]
